# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# Load saved model bundle
bundle = joblib.load("airbnb_price_model.pkl")

model = bundle["model"]
feature_columns = bundle["feature_columns"]
neighbourhood_price_map = bundle["neighbourhood_price_map"]
default_neighbourhood_encoded = bundle["default_neighbourhood_encoded"]

st.title("Airbnb NYC Price Prediction App")
st.write("Enter listing details to estimate the Airbnb price.")

# User inputs
latitude = st.number_input("Latitude", value=40.7128)
longitude = st.number_input("Longitude", value=-74.0060)

neighbourhood_group = st.selectbox(
    "Neighbourhood Group",
    ["Bronx", "Brooklyn", "Manhattan", "Queens", "Staten Island"]
)

neighbourhood = st.selectbox(
    "Neighbourhood",
    sorted(neighbourhood_price_map.keys())
)

room_type = st.selectbox(
    "Room Type",
    ["Entire home/apt", "Private room", "Shared room"]
)

minimum_nights = st.number_input("Minimum Nights", min_value=1, value=1)
number_of_reviews = st.number_input("Number of Reviews", min_value=0, value=0)
reviews_per_month = st.number_input("Reviews per Month", min_value=0.0, value=0.0)
calculated_host_listings_count = st.number_input("Host Listings Count", min_value=1, value=1)
availability_365 = st.number_input("Availability 365", min_value=0, max_value=365, value=100)

if st.button("Predict Price"):

    # Start with all feature columns as 0
    input_data = {col: 0 for col in feature_columns}

    # Numerical features
    input_data["latitude"] = latitude
    input_data["longitude"] = longitude
    input_data["availability_365"] = availability_365

    # Log-transformed features
    input_data["minimum_nights_log"] = np.log1p(minimum_nights)
    input_data["number_of_reviews_log"] = np.log1p(number_of_reviews)
    input_data["reviews_per_month_log"] = np.log1p(reviews_per_month)
    input_data["host_listings_log"] = np.log1p(calculated_host_listings_count)

    # Feature engineering
    input_data["with_reviews"] = 1 if number_of_reviews > 0 else 0

    # One-hot encode room type
    room_col = f"room_type_{room_type}"
    if room_col in input_data:
        input_data[room_col] = 1

    # One-hot encode neighbourhood group
    group_col = f"neighbourhood_group_{neighbourhood_group}"
    if group_col in input_data:
        input_data[group_col] = 1

    # Target encode neighbourhood
    input_data["neighbourhood_encoded"] = neighbourhood_price_map.get(
        neighbourhood,
        default_neighbourhood_encoded
    )

    # Convert to DataFrame in same column order as training
    input_df = pd.DataFrame([input_data])[feature_columns]

    # Predict log price
    predicted_log_price = model.predict(input_df)[0]

    # Convert back to actual price
    predicted_price = np.expm1(predicted_log_price)

    st.subheader("Predicted Airbnb Price")
    st.success(f"Estimated price: ${predicted_price:.2f}")